// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEyMxJQGeELlfgDcoU5VHUTqR1c8EWCs0',
    appId: '1:952640155826:android:bd892c593737286ee199ab',
    messagingSenderId: '952640155826',
    projectId: 'whatsapp-clone-fda5e',
    storageBucket: 'whatsapp-clone-fda5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFtiCrm7x3l0kIsUXEf3tF-mSKnbQdMDM',
    appId: '1:952640155826:ios:4bce46b23002a30de199ab',
    messagingSenderId: '952640155826',
    projectId: 'whatsapp-clone-fda5e',
    storageBucket: 'whatsapp-clone-fda5e.appspot.com',
    iosBundleId: 'com.example.whatsappUi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt0LC_H6mM9GgL-ScwOzB187cogt75nhs',
    appId: '1:952640155826:web:908f659b2eecefa1e199ab',
    messagingSenderId: '952640155826',
    projectId: 'whatsapp-clone-fda5e',
    authDomain: 'whatsapp-clone-fda5e.firebaseapp.com',
    storageBucket: 'whatsapp-clone-fda5e.appspot.com',
    measurementId: 'G-W3PGV82FMD',
  );

}